version: "3.1"

networks:
  net1:

services:
  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: stage
      MYSQL_USER: example
      MYSQL_PASSWORD: secret2


  redis:
    image: redis
    ports:
      - "6379:6379"


