# Generated by Django 4.1 on 2023-12-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user_company_user_is_active_user_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
    ]
